apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: datawiseio/fio
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data: