kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elk
spec:
  type: NodePort
  selector:
    component: elasticsearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: http