apiVersion: v1
data:
  start.sh: |-
    #!/bin/sh
    echo "Cleaning up first"
    rm -rf /storage/*.*
    echo "Running fio job"
    /usr/bin/fio /config/job.fio --output=/storage/test.json --output-format=json
    sleep 5m
  job.fio: |-
    [global]
    ioengine=libaio
    rw=randwrite
    numjobs=8
    direct=1
    bs=4k
    filename=/data/4krandrw1_100g.data
    runtime=1000
    time_based=1
    iodepth=8
    size=100g
    #gtod_reduce=1
    [randwritejob]
kind: ConfigMap
metadata:
  name: fio-configmap