# Logstash deployment that only deploys the sidecar.  This is for testing.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fio-with-logstash-sidecar-deployment
  labels:
    component: fio-with-logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fio-with-logstash
    spec:
      containers:
      # Fio Tester
      - name: fio-test
        image: datawiseio/fio
        volumeMounts:
        - name: fio-test-data-volume 
          mountPath: "/data"
        - name: fio-configmap
          mountPath: "/config"    
        command: ["/usr/bin/fio","/config/job.fio","--output=/data/test.json","--output-format=json"]
        #command: ["/bin/sh","-c","chmod u+x /config/start.sh; /config/start.sh"]
      # Logstash sidecar
      - name: logstash-sidecar
        image: docker.elastic.co/logstash/logstash:5.5.2
        volumeMounts:
        - name: fio-test-data-volume 
          mountPath: "/data"
        - name: logstash-conf
          mountPath: /usr/share/logstash/pipeline
        - name: logstash-yaml
          mountPath: /usr/share/logstash/config
      volumes:
      - name: fio-test-data-volume
        persistentVolumeClaim:
         claimName: fio-test-pvc-ceph
      - name: fio-configmap
        configMap:
          name: fio-configmap
          items:
          - key: job.fio
            path: job.fio
          - key: start.sh
            path: start.sh
      - name: logstash-conf
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: logstash-yaml
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.yml
            path: logstash.yml    
     
  