# Volume Claim -
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-test-pvc
  annotations:
    #volume.alpha.kubernetes.io/storage-class: standard
    v1.storage.k8s.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi