apiVersion: v1
data:
  start.sh: |-
    #!/bin/sh
    echo "Running fio job"
    /usr/bin/fio /config/job.fio --output-format=json
    echo "Done"
    echo "install curl"
    apt-get install -yq curl
    echo "Executing curl"
    curl http://elasticsearch:9200/
  job.fio: |-
    [global]
    ioengine=libaio
    rw=rw
    numjobs=1
    direct=1
    bs=4k
    filename=/data/4krandrw1.data
    runtime=10
    time_based=1
    iodepth=1
    size=1m
    # group_reporting
    [randwritejob]
    # The most basic form of data verification. Write the device randomly
    # in 4K chunks, then read it back and verify the contents.
    [write-and-verify]
    rw=randwrite
    bs=4k
    direct=1
    ioengine=libaio
    iodepth=1
    verify=crc32c
    # Use /dev/XXX. For running this on a file instead, remove the filename
    # option and add a size=32G (or whatever file size you want) instead.
    filename=/data/test-verify.data
    [write-fio-4k-para]
    stonewall
    filename=/data/4kpara-write.data
    rw=write
    write_bw_log=4k-write.results
    write_iops_log=4k-write.results
    write_lat_log=4k-write.resultste  
kind: ConfigMap
metadata:
  name: fio-configmap
  namespace: default