# https://hub.docker.com/r/emacski/k8s-kibana/
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: default
  labels:
    k8s-app: kibana-logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: emacski/k8s-kibana:latest
        resources:
          # keep request = limit to keep this container in guaranteed class
          #limits:
          #  cpu: 100m
          #requests:
          #  cpu: 100m
        env:
          - name: "kibana_elasticsearch_url"
            value: "http://elasticsearch:9200"
          # when using a "-proxy" image, the following is not required
          #- name: "kibana_base_url"
          #  value: "/api/v1/proxy/namespaces/default/services/kibana-logging"
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP