apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: default
  labels:
    #kubernetes.io/name: "kibana-logging"
    #kubernetes.io/cluster-service: "true"
    k8s-app: kibana-logging
spec:
  type: NodePort
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-logging