apiVersion: v1
data:
  logstash.conf: |-
    input { 
      heartbeat {
        message => "sequence"
        interval => 10
        type => "heartbeat"
      }
      file { 
        path => "/data/test.json"
        start_position => "beginning"
      } 
    }
    output {
      elasticsearch { 
        hosts => ["elasticsearch:9200"] 
        index => "logstash-fiotest"
      }
      stdout { codec => rubydebug }
    }
  logstash.yml: |-
    ## Default Logstash configuration from logstash-docker.
    ## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash.yml
    #
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    #xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
    #xpack.monitoring.elasticsearch.username: logstash_system
    #xpack.monitoring.elasticsearch.password: changeme
    ## Disable X-Pack
    ## see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
    ##     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
    #
    xpack.monitoring.enabled: false
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: default