# Logstash deployment that only deploys the sidecar.  This is for testing.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-sidecar
  labels:
    component: logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: logstash
    spec:
      containers:
      - name: logstash-sidecar
        image: docker.elastic.co/logstash/logstash:5.6.1
        volumeMounts:
        - name: logstash-conf
          mountPath: /usr/share/logstash/pipeline
        - name: logstash-yaml
          mountPath: /usr/share/logstash/config
      volumes:
      - name: logstash-conf
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: logstash-yaml
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.yml
            path: logstash.yml
